# Generated by Django 4.0.1 on 2023-07-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('job_link', models.URLField(default='')),
                ('job_type', models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary'), ('Volunteer', 'Volunteer'), ('Other', 'Other')], default='', max_length=200)),
                ('remote_onsite', models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='', max_length=200)),
                ('experience', models.CharField(default='', max_length=200)),
                ('logo', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('location', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=200)),
                ('deadline', models.DateField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
