# Generated by Django 4.0.1 on 2023-07-20 13:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_work', django_countries.fields.CountryField(default='', max_length=2)),
            ],
        ),
    ]
