# Generated by Django 4.0.1 on 2023-07-20 13:35

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_country_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_location',
            name='country_of_work',
            field=django_countries.fields.CountryField(default='select country', max_length=2, null=True),
        ),
    ]
