# Generated by Django 4.0.1 on 2023-07-20 13:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_country_location_country_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_location',
            name='country_of_work',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
